artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: D:\Resarch\2024\temporary\raw.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



prepare_knn_model:
  root_dir: artifacts/prepare_knn_model
  data_file_path: artifacts/data_ingestion/raw/complete_dataset_sample.pkl
  knn_model_path: artifacts/prepare_knn_model/knn_model.h5
  # updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




# prepare_callbacks:
#   root_dir: artifacts/prepare_callbacks
#   tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
#   checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5




# training:
#   root_dir: artifacts/training
#   trained_model_path: artifacts/training/model.h5